services:
  db:
    image: postgres:13-alpine3.20
    port:
      - 5432:5432
    enviroment:
      - POSTGRES_USER=dockeruser
      - POSTGRES_PASSWORD=abc123!
      - POSTGRES_DB=pets
    volumes:
      - pg-data:/vat/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  web:
    image: sun12wook11/nodejs-app
    build: web
    port:
      - 3000:3000
    enviroment:
      - DB_HOST=db
    depends_on:
      - db

volumes:
  pg-data: